{ inputs, ... }:
{
  imports = [
    inputs.zen-browser.homeModules.beta
    ./packages.nix
    ./zen.nix
    ./kitty.nix
    ./fish.nix
    ./catppuccin.nix
    ./starship.nix
    ./git.nix
    ./spicetify.nix
    ./ncspot.nix
    ./hyprland
    ./gh.nix
    ./caelestia.nix
    ./lf/lf.nix
    ./bat.nix
    ./scripts.nix
    ./stylix.nix
    ./btop.nix
    ./cava.nix
    ./ssh.nix
    ./sops.nix
    ./rofi
    ./yazi.nix
    ./xdg.nix
    ./jetbrains.nix
    ./opencode.nix
    ./atuin.nix
    ./zoxide.nix
  ];
}
