{ pkgs, nixvim, ... }:
{
  home.packages = with pkgs; [
    nixvim.packages.${pkgs.system}.default
    tokei
    btop
    bat
    eza
    lf
    sops
    lazygit
    cmake
    hyprpicker
    wf-recorder
    nomacs
    celluloid
    feh
    ffmpeg
    jq
    jetbrains.rider
    glow
    pfetch-rs
    nerdfetch
    fastfetch
    grim
    slurp
    nitch
    cowsay
    pipes-rs
    cava
    ncspot
    google-chrome
    zathura
    swww
    libnotify
    noto-fonts-emoji
    nerd-fonts.jetbrains-mono
    dotnetCorePackages.dotnet_8.sdk # Necessary for rider + omnisharp lsp
  ];
}
